# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
 # Import torch
import torch

# Create random tensor
TENSOR1 = torch.rand(size=[7, 7])
TENSOR1

tensor([[0.8839, 0.8890, 0.5057, 0.4380, 0.8324, 0.5201, 0.1237],
        [0.7606, 0.9653, 0.9685, 0.1336, 0.5492, 0.1025, 0.2681],
        [0.9795, 0.3160, 0.7017, 0.6903, 0.6049, 0.5513, 0.4292],
        [0.7878, 0.8256, 0.9435, 0.3578, 0.7075, 0.7707, 0.3433],
        [0.8721, 0.0615, 0.8021, 0.7347, 0.4520, 0.3352, 0.8760],
        [0.0866, 0.1343, 0.9950, 0.7843, 0.5331, 0.3751, 0.5737],
        [0.5805, 0.4129, 0.8214, 0.4117, 0.5400, 0.4199, 0.9296]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
TENSOR2 = torch.rand(size=[1, 7])

# Perform matrix multiplication
TENSOR2 = TENSOR2.T
TENSOR1.matmul(TENSOR2)

tensor([[2.3317],
        [2.1409],
        [2.3480],
        [2.6651],
        [2.1027],
        [2.0211],
        [2.0342]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
TENSOR_A = torch.rand(size=[7,7])
TENSOR_B = torch.rand(size=[7,1])

# Matrix multiply tensors
TENSOR_A.matmul(TENSOR_B)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
cuda = torch.cuda.is_available()
# Create two random tensors on GPU
tensor_x = torch.rand(size=[2,3]).cuda()
tensor_y = torch.rand(size=[2,3]).cuda()
print(tensor_x, tensor_y)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
out = torch.mm(tensor_x, tensor_y.T)
out

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(torch.max(out))
# Find min
print(torch.min(out))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(torch.argmax(out))
# Find arg min
print(torch.argmax(out))

tensor(3, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [35]:
# Set seed
torch.manual_seed(7)
# Create random tensor
TENSOR = torch.rand([1,1,1,10])
# Remove single dimensions
TENSOR_S = torch.squeeze(TENSOR)
# Print out tensors and their shapes
print(TENSOR)
print(TENSOR.size())
print(TENSOR_S)
print(TENSOR_S.size())


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
