In [16]:
import torch
torch.__version__

'2.9.0+cu126'

In [17]:
#scaler
scaler = torch.tensor(7)
scaler
scaler.ndim

0

In [18]:
#getting integer within tensor - only works with one element tensors
scaler.item()

7

In [19]:
#vector
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [20]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [21]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
#random Tensor
random_tensor = torch.rand([4, 3])
random_tensor, random_tensor.dtype

(tensor([[0.5664, 0.5706, 0.7217],
         [0.2157, 0.0415, 0.2903],
         [0.0052, 0.8127, 0.2556],
         [0.6512, 0.5186, 0.6332]]),
 torch.float32)

In [23]:
#zeros and ones
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype
ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
#range
zero_to_ten = torch.arange(0, 10)
zero_to_ten
zero_to_ten_2 = torch.arange(0, 10, 2)
zero_to_ten_2


tensor([0, 2, 4, 6, 8])

In [25]:
# Stack tensors on top of each other
x = torch.arange(1., 8.)
x, x.shape
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [26]:
print(x_stacked[1, :])

tensor([2., 2., 2., 2.])


In [27]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [28]:
torch.manual_seed(42)
torch.random.manual_seed(seed=42)

tensor_1 = torch.rand(3, 4)
tensor_2 = torch.rand(3, 4)

print(tensor_1)
print(tensor_2)
tensor_1==tensor_2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
import random

# # Set the random seed
RANDOM_SEED=67 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])

Tensor D:
tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [37]:
#GPU
torch.cuda.is_available()


device = "cuda" if torch.cuda.is_available() else "cpu"
device

torch.cuda.device_count()

tensorX = torch.tensor([1, 2, 3])
print(tensorX, tensorX.device)
tensorY = tensor.to(device)
tensorY

tensor([1, 2, 3]) cpu


tensor([1., 2., 3., 4., 5., 6., 7.], device='cuda:0', dtype=torch.float64)

In [40]:
tensorZ = tensorY.cpu()
tensorZ, tensorZ.device

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), device(type='cpu'))